"""add foto_perfil to user

Revision ID: ec0feb84af34
Revises: 
Create Date: 2025-09-03 18:42:21.961152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0feb84af34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lancamentos_transacao'), 'lancamentos', ['transacao'], unique=False)
    op.add_column('user', sa.Column('foto_perfil', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'foto_perfil')
    op.drop_index(op.f('ix_lancamentos_transacao'), table_name='lancamentos')
    # ### end Alembic commands ###
